package br.com.digitala.banco;


// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private Integer idCategoria;
	private String nome;
	private String descricao;
	private String caminhoFoto;

	public Categoria() {
	}

	public Categoria(String nome, String descricao) {
		this.nome = nome;
		this.descricao = descricao;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("idCategoria: " + this.getIdCategoria() + "\n");
		b.append("nomeCategoria: " + this.getNome() + "\n");
		b.append("descricaoCategoria: " + this.getDescricao() + "\n");

		return b.toString();
	}

	public String getCaminhoFoto() {
		return caminhoFoto;
	}

	public void setCaminhoFoto(String caminhoFoto) {
		this.caminhoFoto = caminhoFoto;
	}
}
