package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ItemsPedido generated by hbm2java
 */
public class ItemsPedido implements java.io.Serializable {

	private ItemsPedidoId id;
	private BigDecimal valorProduto;
	private int qtdProduto;

	public ItemsPedido() {
	}

	public ItemsPedido(ItemsPedidoId id, BigDecimal valorProduto, int qtdProduto) {
		this.id = id;
		this.valorProduto = valorProduto;
		this.qtdProduto = qtdProduto;
	}

	public ItemsPedidoId getId() {
		return this.id;
	}

	public void setId(ItemsPedidoId id) {
		this.id = id;
	}

	public BigDecimal getValorProduto() {
		return this.valorProduto;
	}

	public void setValorProduto(BigDecimal valorProduto) {
		this.valorProduto = valorProduto;
	}

	public int getQtdProduto() {
		return this.qtdProduto;
	}

	public void setQtdProduto(int qtdProduto) {
		this.qtdProduto = qtdProduto;
	}

}
