package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

/**
 * ItemsPedidoId generated by hbm2java
 */
public class ItemsPedidoId implements java.io.Serializable {

	private int idPedido;
	private int idProduto;

	public ItemsPedidoId() {
	}

	public ItemsPedidoId(int idPedido, int idProduto) {
		this.idPedido = idPedido;
		this.idProduto = idProduto;
	}

	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public int getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(int idProduto) {
		this.idProduto = idProduto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemsPedidoId))
			return false;
		ItemsPedidoId castOther = (ItemsPedidoId) other;

		return (this.getIdPedido() == castOther.getIdPedido())
				&& (this.getIdProduto() == castOther.getIdProduto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPedido();
		result = 37 * result + this.getIdProduto();
		return result;
	}

}
