package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * OrdemServico generated by hbm2java
 */
public class OrdemServico implements java.io.Serializable {

	private Integer idOrdemServico;
	private Integer idServico;
	private BigDecimal valorTotal;
	private Date dataEntrada;
	private Date dataEntrega;
	private String observacoes;
	private int idStatus;

	public OrdemServico() {
	}

	public OrdemServico(BigDecimal valorTotal, Date dataEntrada,
			Date dataEntrega, int idStatus) {
		this.valorTotal = valorTotal;
		this.dataEntrada = dataEntrada;
		this.dataEntrega = dataEntrega;
		this.idStatus = idStatus;
	}

	public OrdemServico(Integer idServico, BigDecimal valorTotal,
			Date dataEntrada, Date dataEntrega, String observacoes, int idStatus) {
		this.idServico = idServico;
		this.valorTotal = valorTotal;
		this.dataEntrada = dataEntrada;
		this.dataEntrega = dataEntrega;
		this.observacoes = observacoes;
		this.idStatus = idStatus;
	}

	public Integer getIdOrdemServico() {
		return this.idOrdemServico;
	}

	public void setIdOrdemServico(Integer idOrdemServico) {
		this.idOrdemServico = idOrdemServico;
	}

	public Integer getIdServico() {
		return this.idServico;
	}

	public void setIdServico(Integer idServico) {
		this.idServico = idServico;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Date getDataEntrada() {
		return this.dataEntrada;
	}

	public void setDataEntrada(Date dataEntrada) {
		this.dataEntrada = dataEntrada;
	}

	public Date getDataEntrega() {
		return this.dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

	public int getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(int idStatus) {
		this.idStatus = idStatus;
	}

}
