package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

/**
 * PedidoId generated by hbm2java
 */
public class PedidoId implements java.io.Serializable {

	private int idpedido;
	private int idCliente;

	public PedidoId() {
	}

	public PedidoId(int idpedido, int idCliente) {
		this.idpedido = idpedido;
		this.idCliente = idCliente;
	}

	public int getIdpedido() {
		return this.idpedido;
	}

	public void setIdpedido(int idpedido) {
		this.idpedido = idpedido;
	}

	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedidoId))
			return false;
		PedidoId castOther = (PedidoId) other;

		return (this.getIdpedido() == castOther.getIdpedido())
				&& (this.getIdCliente() == castOther.getIdCliente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdpedido();
		result = 37 * result + this.getIdCliente();
		return result;
	}

}
