package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

	private PedidoId id;
	private int idStatus;
	private BigDecimal valorTotal;
	private Date dataPedido;
	private String observacoes;
	private List<ItemsPedido> itemsPedido;

	public Pedido() {
	}

	public Pedido(PedidoId id, int idStatus, BigDecimal valorTotal,
			Date dataPedido) {
		this.id = id;
		this.idStatus = idStatus;
		this.valorTotal = valorTotal;
		this.dataPedido = dataPedido;
	}

	public Pedido(PedidoId id, int idStatus, BigDecimal valorTotal,
			Date dataPedido, String observacoes) {
		this.id = id;
		this.idStatus = idStatus;
		this.valorTotal = valorTotal;
		this.dataPedido = dataPedido;
		this.observacoes = observacoes;
	}

	public PedidoId getId() {
		return this.id;
	}

	public void setId(PedidoId id) {
		this.id = id;
	}

	public int getIdStatus() {
		return this.idStatus;
	}

	public void setIdStatus(int idStatus) {
		this.idStatus = idStatus;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Date getDataPedido() {
		return this.dataPedido;
	}

	public void setDataPedido(Date dataPedido) {
		this.dataPedido = dataPedido;
	}

	public String getObservacoes() {
		return this.observacoes;
	}

	public void setObservacoes(String observacoes) {
		this.observacoes = observacoes;
	}

	public List<ItemsPedido> getItemsPedido() {
		return itemsPedido;
	}

	public void setItemsPedido(List<ItemsPedido> itemsPedido) {
		this.itemsPedido = itemsPedido;
	}

}
