package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1


/**
 * Produto generated by hbm2java
 */
public class Produto implements java.io.Serializable {

	private Integer idProduto;
	private Integer idCategoria;
	private String nome;
	private String descricao;
	private String marca;
	private String modelo;
	private Float valorUnitario;
	private Float valorAtacado;
	private String codigo;
	private String destaque;

	private String caminhoFoto;

	public Produto() {
	}

	public Produto(String nome, String descricao, Float valorProduto, Integer idCategoria) {
		this.nome = nome;
		this.descricao = descricao;
		this.valorUnitario = valorProduto;
		this.idCategoria = idCategoria;
	}

	public Produto(String nome, String descricao, String marca, String modelo,
			Float valorProduto, Integer idCategoria) {
		this.nome = nome;
		this.descricao = descricao;
		this.marca = marca;
		this.modelo = modelo;
		this.valorUnitario = valorProduto;
		this.idCategoria = idCategoria;
	}

	public Integer getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(Integer idProduto) {
		this.idProduto = idProduto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public Float getValorUnitario() {
		return valorUnitario;
	}

	public void setValorUnitario(Float valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public Float getValorAtacado() {
		return valorAtacado;
	}

	public void setValorAtacado(Float valorAtacado) {
		this.valorAtacado = valorAtacado;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getCaminhoFoto() {
		return caminhoFoto;
	}

	public void setCaminhoFoto(String caminhoFoto) {
		this.caminhoFoto = caminhoFoto;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDestaque() {
		return destaque;
	}

	public void setDestaque(String destaque) {
		this.destaque = destaque;
	}

}
