package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Produto generated by hbm2java
 */
public class Produto implements java.io.Serializable {

	private Integer idProduto;
	private String nome;
	private String descricao;
	private String marca;
	private String modelo;
	private BigDecimal valorProduto;
	private String caminhoFoto;
	private int idCategoria;

	public Produto() {
	}

	public Produto(String nome, String descricao, BigDecimal valorProduto,
			int idCategoria) {
		this.nome = nome;
		this.descricao = descricao;
		this.valorProduto = valorProduto;
		this.idCategoria = idCategoria;
	}

	public Produto(String nome, String descricao, String marca, String modelo,
			BigDecimal valorProduto, int idCategoria) {
		this.nome = nome;
		this.descricao = descricao;
		this.marca = marca;
		this.modelo = modelo;
		this.valorProduto = valorProduto;
		this.idCategoria = idCategoria;
	}

	public Integer getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(Integer idProduto) {
		this.idProduto = idProduto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public BigDecimal getValorProduto() {
		return this.valorProduto;
	}

	public void setValorProduto(BigDecimal valorProduto) {
		this.valorProduto = valorProduto;
	}

	public int getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(int idCategoria) {
		this.idCategoria = idCategoria;
	}

	public String getCaminhoFoto() {
		return caminhoFoto;
	}

	public void setCaminhoFoto(String caminhoFoto) {
		this.caminhoFoto = caminhoFoto;
	}

}
