package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Servico generated by hbm2java
 */
public class Servico implements java.io.Serializable {

	private Integer idServico;
	private String nome;
	private String descricao;
	private BigDecimal valorServico;

	public Servico() {
	}

	public Servico(String nome, String descricao, BigDecimal valorServico) {
		this.nome = nome;
		this.descricao = descricao;
		this.valorServico = valorServico;
	}

	public Integer getIdServico() {
		return this.idServico;
	}

	public void setIdServico(Integer idServico) {
		this.idServico = idServico;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public BigDecimal getValorServico() {
		return this.valorServico;
	}

	public void setValorServico(BigDecimal valorServico) {
		this.valorServico = valorServico;
	}

}
