package br.com.digitala.banco;

// Generated 04/06/2015 11:21:49 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ValorProduto generated by hbm2java
 */
public class ValorProduto implements java.io.Serializable {

	private Integer idvalorProduto;
	private int idProduto;
	private int idEmpresa;
	private BigDecimal valorProduto;

	public ValorProduto() {
	}

	public ValorProduto(int idProduto, int idEmpresa, BigDecimal valorProduto) {
		this.idProduto = idProduto;
		this.idEmpresa = idEmpresa;
		this.valorProduto = valorProduto;
	}

	public Integer getIdvalorProduto() {
		return this.idvalorProduto;
	}

	public void setIdvalorProduto(Integer idvalorProduto) {
		this.idvalorProduto = idvalorProduto;
	}

	public int getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(int idProduto) {
		this.idProduto = idProduto;
	}

	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public BigDecimal getValorProduto() {
		return this.valorProduto;
	}

	public void setValorProduto(BigDecimal valorProduto) {
		this.valorProduto = valorProduto;
	}

}
